name: Automerge PRs

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: 'pascalgn/automerge-action@v0.16.2'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'automerge'
          MERGE_METHOD: 'merge'
          MERGE_COMMIT_MESSAGE: 'pull-request-title'
          MERGE_RETRIES: 3
          MERGE_RETRY_SLEEP: 10000
