name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update branch
          title: automated PR to main
          body: this is an automated pull request to update the main branch with changes from dev.
          branch: pr-branch-${{ github.run_id }}
          base: main
          labels: automerge
