name: Dev to Main Sync, Automerge, and Deploy

on:
  push:
    branches: ['dev']
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  workflow:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Reset main to dev
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: sync-main-${{ github.run_number }}
          base: main
          title: 'Sync main with dev'
          body: 'Automated PR to update main branch with changes from dev.'
          labels: automerge
          commit-message: 'Update main with changes from dev'

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Merge Pull Request
        run: |
          PR_URL=$(echo ${{ steps.create_pr.outputs.pull-request-url }} | awk -F '/' '{print $(NF-1) "/" $NF}')
          gh pr merge "$PR_URL" --auto --merge

      - name: Set up Node
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        if: github.ref == 'refs/heads/main'
        run: npm ci

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
